const languages = {
  ru: {
    header: {
      search: "Поиск",
      products: "Продукты",
    },
    sitebar: {
      productList: "Список продуктов",
      category: "Категории",
      atribut: "Атрибуты",
      order: "Заказы",
      recall: "Обратный связ",
      settings: "Настройки сайта",
      users: "Пользователь",
      exit: "Выйти",
    },
    main: {
      filter: "Фильтр",
      id: "Ид",
      searchProduct: "Поиск товара ",
      searchOrder: "Поиск Заказы",
      searchCategory: "Поиск Категори",
      searchAttribute: "Поиск Атрибуты",
      searchUser: "Поиск Обратный связ",
      searchAdmin: "Поиск пользователь",
      categoryProduct: "Категория продукта",
      nameUser: "Имя клиента",
      birthday: "Дата рождение",
      roleUser: "Роль ползователя",
      lastActive: "Последний активность",
      contactInfo: "Контактная информация",
      socialMedia: "Cоциальные сети",
      sort: "Сортировка",
      as: "По А-Я",
      add: "Добавить",
      select: "Выбрано",
      productName: "Название товара",
      lookas: "Вид формы",
      valueAtt: "Значение атрибута",
      price: "Цена",
      numOrder: "№ Заказа",
      salePrice: "Цена со скидкой",
      quantity: "Кол-во",
      size: "Размер",
      volume: "Объем",
      status: "Статус",
      elementsPage: "Элементы на каждой странице",
      itemsNumb: " из  предметов",
      pages: "из  страниц",
      sum: "сум",
      delete: "Удалить",
      addProduct: "Добавить продукт",
      information: "Информация",
      picture: "Изображение",
      colvo: "Кол-во под категория",
      subCat: "Под категории",
      phone: "Tелефон",
      address: "Адрес",
      product: "Товары",
      ovarallPrice: "Обшая цена",
      timeOrder: "Время заказа",
      schedule: "График работы",
      langSite: "Языки сайта",
      defaultLang: "Язык по умолчанию",
      langRu: "Pусский язык",
      langUz: "Узбекский язык",
      langEn: "Aнглийский язык",
    },
  },
  en: {
    header: {
      search: "Search",
      products: "Products",
    },
    sitebar: {
      productList: "Products Lists",
      category: "Category",
      atribut: "Attribute",
      order: "Order",
      recall: "Feedback",
      settings: "Site settings",
      users: "Users",
      exit: "Exit",
    },

    main: {
      filter: "Filter",
      searchProduct: "Search products ",
      searchOrder: "Search Order ",
      searchCategory: "Search Category",
      searchAttribute: "Search Attribute",
      searchUser: "Search Feedback",
      searchAdmin: "Search Admin/User",
      categoryProduct: "Category Products",
      nameUser: "Client name",
      lookas: "Form type",
      valueAtt: "Attribute value",
      numOrder: "№ Order",
      sort: "Sort",
      as: "By A-Z",
      add: "Add",
      select: "Selected",
      productName: "Product Name",
      price: "Price",
      salePrice: "Sale Price",
      quantity: "Q-ty",
      size: "Size",
      volume: "Volume",
      status: "Status",
      elementsPage: "Elements on each page",
      itemsNumb: " out of  items",
      pages: "of  pages",
      sum: "sum",
      delete: "Delete",
      addProduct: "Add Products",
      information: "Information",
      picture: "Picture",
      colvo: "Q-ty sub category",
      subCat: "Sub categories",
      phone: "Phone",
      address: "Address",
      product: "Products",
      ovarallPrice: "Total price",
      timeOrder: "Order time",
      birthday: "Date of birth",
      roleUser: "User role",
      lastActive: "Last Activity",
      contactInfo: "Contact Information",
      socialMedia: "Social networks",
      schedule: "Schedule",
      langSite: "Site Languages",
      langRu: "Russian language",
      langUz: "Uzbek language",
      langEn: "English language",
      defaultLang: "Default language",
    },
  },
  uz: {
    header: {
      search: "Qidiruv",
      products: "Mahsulotlar",
    },
    sitebar: {
      productList: "Mahsulotlar ro'yxati",
      category: "Kategoriyalar",
      atribut: "Attributlar",
      order: "Buyurtma",
      recall: "Fikr-mulohaza",
      settings: "Sayt sozlamalari",
      users: "Foydalanuvchilar",
      exit: "Chiqish",
    },

    main: {
      filter: "Filter",
      searchProduct: "Mahsulot qidirish",
      searchOrder: "Buyurtma qidirish",
      searchCategory: "Kategoriya qidirish",
      searchAttribute: "Atribut qidirish",
      searchUser: "Foydalanuvchi qidirish",
      searchAdmin: "Foydalanuvchi qidirish",
      categoryProduct: "Mahsulotlar Kategoriyasi",
      lookas: "Shakl turi",
      valueAtt: "Atribut qiymati",
      numOrder: "№ Buyurtma",
      nameUser: "Mijoz ismi",
      sort: "Saralash",
      as: "A-Z tomonidan",
      add: "Qo'shish",
      select: "Tanlangan",
      productName: "Mahsulot nomi",
      price: "Narx",
      salePrice: "Chegirma narx",
      quantity: "Soni",
      size: "O'lcham",
      volume: "Hajm",
      status: "Status",
      elementsPage: "Har bir sahifadagi elementlar",
      itemsNumb: " elementdan  tasi",
      pages: " sahifadan iborat",
      sum: "so'm",
      delete: "O'chirish",
      addProduct: "Mahsulot qo'shish",
      information: "Ma'lumot",
      picture: "Rasm",
      colvo: "Kategoriya bo'yicha soni",
      subCat: "Sub kategoriyalar",
      phone: "Telefon",
      address: "Manzil",
      product: "Mahsulotlar",
      ovarallPrice: "Umumiy narx",
      timeOrder: "Buyurtma vaqti",
      birthday: "Tug'ilgan sana",
      roleUser: "Foydalanuvchi roli",
      lastActive: "Oxirgi faoliyat",
      contactInfo: "Bog'lanish uchun ma'lumot",
      socialMedia: "Ijtimoit Tarmoqlar",
      schedule: "Ish grafigi",
      langSite: "Sayt tillari",
      defaultLang: "Standart til",
      langRu: "Rus tili",
      langUz: "O'zbek tili",
      langEn: "Ingliz tili",
    },
  },
};

export default languages;
